# -*- coding: utf-8 -*-
"""ÑA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMDLpGD9pZO2XyHvMpjxffeOgAQocs5M
"""

import random
datos_sobre_mi = [
"Mi afición favorita es escuchar musica de Soda Stereo y Gustavo Cerati.",
"Tengo la mascota mas linda del universo el cual es un perrito que siempre me acompana cuando programo.",
"El proyecto del que más orgulloso me siento es un juego que programé llamado 'Galactic Defender'.",
"Mi plato favorito es la pizza con mucho queso",
"Me gusta aprender cosas nuevas sobre programacion y compartirlas con mis mejores amigos o con mi familia."
]


dato_aleatorio = random.choice(datos_sobre_mi)
print(dato_aleatorio)